# Лабораторна робота "Операції над масивами NumPy"

__Метою__ лабораторної роботи є набуття практичних навичок та закріплення теоретичних знань по обробці великих однорідних наборів даних які розташовані у вигляді масивів бібліотеки __NumPy__.

Виконати послідовно завдання в секціях, попередню засвоївши наведені приклади
В завданнях продовжити написання коду замість `...`. 

__Імена змінних в завданнях змінювати не можна!__

### Предвстановлення

In [1]:
# Імпортувати бібліотеку numpy з аліасом np
import numpy as np

In [2]:
# Вивід таблиці відповідності кодів типів даних в NumPy
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)

dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

## 1. Створення та інспектування _np-массивів_

### ПРИКЛАДИ

In [3]:
# Створити 1-вимірний масив з 5 цілочисельних елементів 
arr = np.array([23, 42, 13, 7, 0])

In [4]:
# Інспектування массива
np.info(arr)

class:  ndarray
shape:  (5,)
strides:  (4,)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x23e9fc0b090
byteorder:  little
byteswap:  False
type: int32


In [5]:
# створити 2-мірний масив з цілим типом даних у 2-х байтовому форматі
arr = np.array([[1,2,3], [4,5,6]], dtype='i2')
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# створити масив із  значень в інтервалі 0 - 20 з кроком 2
# np.arange(start, stop, step)
arr = np.arange(0, 20, 2)  
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
# створити масив із 20 рівномірно розміщених значень в інтервалі 0 - 10 
# np.linspace(start, stop, num_of_elements) 
arr = np.linspace(0, 10, 20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [8]:
# створити масив 3х3 випадкових значень 
arr = np.random.rand(3, 3)
print(arr)

[[0.05507947 0.07617653 0.49371863]
 [0.5456187  0.73275503 0.51073714]
 [0.36692359 0.74064731 0.21972723]]


In [9]:
# створення нульвих, одиничних та заповнених масивів
zeros = np.zeros((2,3), dtype='i4')
print(zeros)
ones = np.ones((2,3))
print(ones)
filled = np.full((2,3), 123)
print(filled)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[123 123 123]
 [123 123 123]]


In [10]:
print(arr, end="\n...\n")
# інспектування типу массиву `dtype`
print(arr.dtype)
# інспектування розмірності массиву `shape`
print(arr.shape)
# інспектування довжини масиву `len`
print(len(arr))
# інспектування кількості вимірів масиву `ndim`
print(arr.ndim)
# інспектування кількості елементів в масиві `size`
print(arr.size)
# інспектування коількості байтів на елемент `itemsize`
print(arr.itemsize)
# інспектування кількості пам'яти під масив `nbytes`
print(arr.nbytes)

[[0.05507947 0.07617653 0.49371863]
 [0.5456187  0.73275503 0.51073714]
 [0.36692359 0.74064731 0.21972723]]
...
float64
(3, 3)
3
2
9
8
72


In [11]:
arr.__sizeof__()

200

### ЗАВДАННЯ 1

In [12]:
### ЗАВДАННЯ 1.1: створити та проінспектувати масив 3х4 з ім'ям arr1_1, який містить числа з плавоючою точкою 
arr1_1 = np.array([[2.45, 5.48, 8.14, 7.87],
                  [6.25, 3.14, 9.36, 12.65],
                  [1.49, 7.96, 3.47, 10.34]])
print(arr1_1)
np.info(arr1_1)

[[ 2.45  5.48  8.14  7.87]
 [ 6.25  3.14  9.36 12.65]
 [ 1.49  7.96  3.47 10.34]]
class:  ndarray
shape:  (3, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x23e9e944cb0
byteorder:  little
byteswap:  False
type: float64


In [13]:
### ЗАВДАННЯ 1.2: створити одномірний масив з 5 строкових елементів
arr1_2 = np.array(['понеділок', 'вівторок', 'середа', 'четвер', "п'ятниця"])
print(arr1_2)

['понеділок' 'вівторок' 'середа' 'четвер' "п'ятниця"]


In [14]:
### ЗАВДАННЯ 1.3: створити одиничний масив 3х4 чисел з плаваючою точкою
arr1_3 = np.ones((3, 4))
print(arr1_3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 2. Перетворення форми та типу массивів

### ПРИКЛАДИ

In [15]:
# створити 2-мірний float-масив (2х5) з лінійного int-списка 
spisok = list(range(0,10))
arr = np.array(spisok)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#преретворити форму масива `reshape` 
arr = arr.reshape((2,5))
print(arr)
print(arr.dtype)

[[0 1 2 3 4]
 [5 6 7 8 9]]
int32


In [17]:
# -- 3 перетворити тип масива `astype`
arr = arr.astype('float64')
print(arr)
print(arr.dtype)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
float64


In [18]:
# 'вирівняти' 2-мірний масив
arr = arr.flatten()
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


### ЗАВДАННЯ 2

In [19]:
### ЗАВДАННЯ 2.1: створити 3-мірний масив (3х1х3) логічного 'False'
arr2_1 = np.zeros((3, 1, 3), dtype=bool)
print(arr2_1)

[[[False False False]]

 [[False False False]]

 [[False False False]]]


In [21]:
### ЗАВДАННЯ 2.2: перетворити масив arr2_1 в 2-мірний масив (3х3) типу int
arr2_2 = arr2_1.reshape(3, 3).astype(int)
print(arr2_2)
print(arr2_2.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32


In [23]:
### ЗАВДАННЯ 2.3: створити  2-мірний масив парних чисел в інтервалі 10-21
a = []
for i in range(10,22):
    if i % 2 == 0:
        a.append(i)
arr2_3 = np.array(a).reshape(2, 3)
print(arr2_3)

[[10 12 14]
 [16 18 20]]


## 3. Доступ до  елементів масива

### ПРИКЛАДИ

In [24]:
arr = np.array([10, 6, 7, 21, 44]) 
print(arr)

# 1-й елемент 
print(arr[0])
# 3-й елемент
print(arr[2])
# останній елемент
print(arr[-1])

[10  6  7 21 44]
10
7
44


In [25]:
# створити 2-мірний масив з цілих чисел з інтервалу 10-50
arr = np.random.randint(10, 50, (4,4))
print(arr)

[[49 24 33 36]
 [42 46 14 33]
 [42 18 47 15]
 [43 29 45 16]]


In [26]:
# отримати значення останнього елемента в 2 рядку
el = arr[1, -1]
print(el)

33


In [27]:
# отримати значення останнього рядка
vect = arr[-1]
print(vect)

[43 29 45 16]


In [28]:
# отримати `зріз` з 1 по 2 рядок
mat = arr[0:2]
print(mat)

[[49 24 33 36]
 [42 46 14 33]]


In [29]:
# вилучити 2 та 3 стовбчики `arr`
mat = arr[0:4, 1:3]
print(mat)

[[24 33]
 [46 14]
 [18 47]
 [29 45]]


In [30]:
# вилучити непарні рядки `arr`
mat = arr[0:4:2]
print(mat)

[[49 24 33 36]
 [42 18 47 15]]


In [31]:
# фільтрувати елементи масива за умовою
els = arr[arr > 20]
print(els)

[49 24 33 36 42 46 33 42 47 43 29 45]


### ЗАВДАННЯ 3

In [38]:
### ЗАВДАННЯ 3.1: створити масив 4х5 нормально розподілений випадкових чисел 3 інтервалу [10 - 100]
mu, sigma = 60, 15
arr3_1 = np.random.normal(mu, sigma, (4,5))
arr3_1 = np.clip(arr3_1, 10, 100)
arr3_1 = np.round(arr3_1, 3)
print(arr3_1)

[[41.688 71.214 63.266 93.016 45.39 ]
 [66.582 38.671 95.47  43.18  72.309]
 [56.005 55.081 73.995 55.477 23.503]
 [52.072 64.499 54.48  36.907 64.191]]


In [39]:
### ЗАВДАННЯ 3.2:  вивести 3-елемент в 2-му рядку
el3_2 = arr3_1[1, 2]
print(el3_2)

95.47


In [40]:
### ЗАВДАННЯ 3.3:  вивести 2-й рядок масива `arr3_1`
vect3_3 = arr3_1[1]
print(vect3_3)

[66.582 38.671 95.47  43.18  72.309]


In [42]:
### ЗАВДАННЯ 3.4:  вивести 3 колонку масива `arr3_1`
vect3_4 = arr3_1[0:4, 2]
print(vect3_4)

[63.266 95.47  73.995 54.48 ]


In [43]:
### ЗАВДАННЯ 3.5: вивести матрицю  з 2 та 3 рядка та 2 та 3 колонки масива `arr3_1`
mat3_5 = arr3_1[1:3, 1:3]
print(mat3_5)

[[38.671 95.47 ]
 [55.081 73.995]]


## 4. Матричні компоненти масива

### ПРИКЛАДИ

In [44]:
# створити одиничну матрицю розміру 3х3
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [45]:
# створити матрицю із заданою диагоналлю
mat = np.diag([1,2,3,4,5])
print(mat)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [46]:
# вилучити головну діагональ матриці `diag`
mat = np.random.rand(5,5)
print(mat, end="\n...\n")
print(np.diag(mat))

[[0.05175945 0.34201745 0.87137674 0.14101998 0.22412095]
 [0.85701638 0.96288679 0.58978726 0.23037659 0.05515979]
 [0.76045627 0.35366958 0.70825584 0.99378868 0.03733395]
 [0.68245792 0.50566688 0.10158284 0.23875661 0.08242297]
 [0.18676481 0.33523852 0.05515013 0.33361565 0.37147429]]
...
[0.05175945 0.96288679 0.70825584 0.23875661 0.37147429]


In [47]:
# транспонувати матрицю `mat` (https://ru.wikipedia.org/wiki/Транспонированная_матрица)
mT = np.transpose(mat)
print(mT)

[[0.05175945 0.85701638 0.76045627 0.68245792 0.18676481]
 [0.34201745 0.96288679 0.35366958 0.50566688 0.33523852]
 [0.87137674 0.58978726 0.70825584 0.10158284 0.05515013]
 [0.14101998 0.23037659 0.99378868 0.23875661 0.33361565]
 [0.22412095 0.05515979 0.03733395 0.08242297 0.37147429]]


In [48]:
# отримати детермінант матриці `det` (https://ru.wikipedia.org/wiki/Определитель)
print(np.linalg.det(mat))

0.04081739234270438


In [49]:
# отримати зворотню матриці `det` (https://ru.wikipedia.org/wiki/Обратная_матрица)
invM = np.linalg.inv(mat)
print(invM)

[[ 1.7103638  -2.94546877 -0.35830357  5.94768512 -1.8782078 ]
 [-2.20526519  3.95719835  0.03815229 -5.37314505  1.93126181]
 [ 1.56095589 -0.76497374  0.05838117  1.070445   -1.0715573 ]
 [-1.7285139   1.51621084  1.26269569 -3.58678591  1.48665589]
 [ 2.4508464  -3.33842392 -0.99696372  4.92103944  0.71734341]]


### ЗАВАДАННЯ 4

In [50]:
# ЗАВДАННЯ 4.1: створити квадратну матрицю з 36 рівномірно розподілених цілих 
# елементів з інтервалу 100 - 200
mat4_1 = np.random.randint(100, 201, (6,6))
print(mat4_1)

[[109 108 110 115 177 180]
 [110 198 101 185 111 159]
 [124 103 176 183 155 153]
 [158 115 197 196 123 103]
 [158 183 193 132 138 135]
 [146 123 136 171 124 101]]


In [51]:
# ЗАВДАННЯ 4.2: вивести головну діагональ матниці `mat4_1`
diag4_2 = np.diag(mat4_1)
print(diag4_2)

[109 198 176 196 138 101]


In [52]:
# ЗАВДАННЯ 4.3: транспонувати матрицю 'mat4_1'
trans4_3 = np.transpose(mat4_1)
print(trans4_3)

[[109 110 124 158 158 146]
 [108 198 103 115 183 123]
 [110 101 176 197 193 136]
 [115 185 183 196 132 171]
 [177 111 155 123 138 124]
 [180 159 153 103 135 101]]


In [53]:
# ЗАВДАННЯ 4.4: вирахувати зворотню до 'mat4_1' матрицю 
inv4_4 = np.linalg.inv(mat4_1)
print(inv4_4)

[[ 0.05127371  0.00920791 -0.08451     0.094802   -0.02101663 -0.04644215]
 [-0.02592148 -0.0024225   0.03238109 -0.05002406  0.01635363  0.03011363]
 [-0.01086712 -0.00382844  0.01735109 -0.00780017  0.00928342 -0.00534414]
 [-0.01237724  0.00179854  0.01742757 -0.01474891 -0.00462685  0.01405226]
 [-0.04734359 -0.02176172  0.08122088 -0.112289    0.02291586  0.07947814]
 [ 0.05116259  0.01846716 -0.06985807  0.09721376 -0.02233653 -0.07381035]]


## 5. Операції над масивами

### ПРИКЛАДИ

In [54]:
# задати вектор з 10 елементів
vect = np.array([1, 3, 2, -3, 5, 0])

In [56]:
# вирахувати суму елеметнів
s = np.sum(vect)

# знайти мінімальний ел-т
m = np.min(vect)

# відсортувати вектор по зростанню
vs = np.sort(vect)

# знайти середнє значення
mid = np.average(vect)

print(vect)
print(s)
print(m)
print(vs)
print(mid)

[ 1  3  2 -3  5  0]
8
-3
[-3  0  1  2  3  5]
1.3333333333333333


In [57]:
# матриця 3х3 сконструйована різними методами
mat = np.array([np.arange(1,4), [-2, 4, 6], np.full(3,77)])
print(mat)

[[ 1  2  3]
 [-2  4  6]
 [77 77 77]]


In [58]:
# сума по колонкам `axis=0`
s = np.sum(mat, axis=0)
print(s)

[76 83 86]


In [59]:
# мінімум по рядкам
m = np.min(mat, axis=1)
print(m)

[ 1 -2 77]


In [60]:
# збільшити ел-ти масива вдвічі
v2 = mat * 2
print(v2)

[[  2   4   6]
 [ -4   8  12]
 [154 154 154]]


In [61]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(M, N, sep="\n")

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [62]:
# перемножити елементи матриць M, N
K = M * N
print(K)
# або ->
K = np.multiply(N, M)
print(K)

[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]
[[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


In [63]:
# поелементний поділ
K = N / M
print(K)

[[ 1.          0.5         0.33333333]
 [ 0.5        -0.66666667  0.33333333]
 [ 0.42857143  0.375              inf]]


C:\Users\Katya\AppData\Local\Temp\ipykernel_7688\3347190385.py:2: RuntimeWarning: divide by zero encountered in divide
  K = N / M


In [64]:
# скалярне множення матриць (https://ru.wikipedia.org/wiki/Умножение_матриц)
prod = np.dot(N, M)
print(prod)

[[12  7  9]
 [24 14 18]
 [36 21 27]]


In [65]:
# возвести матрицю `prod` в ступінь 3
pmat = np.linalg.matrix_power(prod, 3)
print(pmat)

[[ 33708  19663  25281]
 [ 67416  39326  50562]
 [101124  58989  75843]]


In [66]:
# додати елементи до 1-вимірного масива
mat = np.array([1,2,3])
mat = np.append(mat, [5,6,7,8])
print(mat)

[1 2 3 5 6 7 8]


In [67]:
# вставити елемент `4` в масив після 3-го елемента
mat = np.insert(mat, 3, 4)
print(mat)

[1 2 3 4 5 6 7 8]


In [68]:
# видалити елемент з індексом 6
mat = np.delete(mat, 6)
print(mat)

[1 2 3 4 5 6 8]


In [69]:
#  копіювання та присвоювання масивів
M = np.random.randint(1, 10, 5 )
print(M)

# присвоїти масив `M` в `N`
N = M
print(N)
print(id(M), id(N))

# копіювати масив `M` в `K`
K = np.copy(M)
print(K)
print(id(M), id(K))

[4 3 9 7 9]
[4 3 9 7 9]
2468036534896 2468036534896
[4 3 9 7 9]
2468036534896 2468036652560


In [70]:
# конкатенація масивів по рядкам
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)
# по колонкам `axis = 1`
arr4 = np.concatenate((arr1, arr2), axis=1)
print(arr4)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


### ЗАВДАННЯ 5

In [73]:
# ЗАВДАННЯ 5.1: просумувати по рядкам масив випадкових чисел розмірностю 3х4
mat5_1 = np.random.randint(10, 61, (3,4))
sum_mat5_1 = np.sum(mat5_1, axis = 1)
print(mat5_1)
print("Сума по рядках: ", sum_mat5_1)

[[30 40 35 21]
 [20 35 58 14]
 [10 37 48 51]]
Сума по рядках:  [126 127 146]


In [78]:
# ЗАВДАННЯ 5.2: знайти мінімальний елемент матриці `sum_mat5_1`
min_sum_mat5_1 = np.min(sum_mat5_1)
print(min_sum_mat5_1)

126


In [80]:
# ЗАВДАННЯ 5.3: створити масив додавши до елементів `mat5_1`  число 100
mat5_3 = np.add(mat5_1, 100)
print(mat5_3)

[[130 140 135 121]
 [120 135 158 114]
 [110 137 148 151]]


In [90]:
# ЗАВДАННЯ 5.4: помножити матрицю `mat5_1` на головну діагональ матриці `mat5_3`
mat5_1 = np.transpose(mat5_1) # щоб підходила розмірність
mat5_4 = np.dot(mat5_1, np.diag(mat5_3)).reshape(4,1)
print(mat5_4)

[[ 8080]
 [15401]
 [19484]
 [12168]]


In [93]:
# ЗАВДАННЯ 5.5: додати справа до матриці `mat5_3` матрицю `mat5_4` 
# вивести ранг отриманої матриці
mat5_3 = np.transpose(mat5_3)
mat5_5 = np.concatenate((mat5_3, mat5_4), axis=1)
rank = np.linalg.matrix_rank(mat5_5)
print(mat5_5)
print("Ранг: ", rank)

[[  130   120   110  8080]
 [  140   135   137 15401]
 [  135   158   148 19484]
 [  121   114   151 12168]]
Ранг:  4
